// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/Luis-Miguel-BL/go-lm-template/internal/domain/lead/model"
)

// LeadRepository is an autogenerated mock type for the LeadRepository type
type LeadRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, leadID
func (_m *LeadRepository) GetByID(ctx context.Context, leadID string) (*model.Lead, error) {
	ret := _m.Called(ctx, leadID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Lead
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Lead, error)); ok {
		return rf(ctx, leadID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Lead); ok {
		r0 = rf(ctx, leadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Lead)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, leadID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *LeadRepository) Save(ctx context.Context, _a1 *model.Lead) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Lead) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeadRepository creates a new instance of LeadRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeadRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeadRepository {
	mock := &LeadRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
