// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/Luis-Miguel-BL/go-lm-template/internal/application/dto"
	mock "github.com/stretchr/testify/mock"

	service "github.com/Luis-Miguel-BL/go-lm-template/internal/application/service"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: ctx
func (_m *AuthService) GenerateToken(ctx context.Context) (dto.AccessToken, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 dto.AccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dto.AccessToken, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dto.AccessToken); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dto.AccessToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: ctx, claims
func (_m *AuthService) RefreshToken(ctx context.Context, claims *service.TokenClaims) (dto.AccessToken, error) {
	ret := _m.Called(ctx, claims)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 dto.AccessToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.TokenClaims) (dto.AccessToken, error)); ok {
		return rf(ctx, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.TokenClaims) dto.AccessToken); ok {
		r0 = rf(ctx, claims)
	} else {
		r0 = ret.Get(0).(dto.AccessToken)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.TokenClaims) error); ok {
		r1 = rf(ctx, claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAppKey provides a mock function with given fields: ctx, appKey
func (_m *AuthService) ValidateAppKey(ctx context.Context, appKey string) bool {
	ret := _m.Called(ctx, appKey)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAppKey")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, appKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ValidateToken provides a mock function with given fields: ctx, token
func (_m *AuthService) ValidateToken(ctx context.Context, token string) (*service.TokenClaims, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *service.TokenClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.TokenClaims, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.TokenClaims); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.TokenClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
