// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// JWTHelper is an autogenerated mock type for the JWTHelper type
type JWTHelper[Claims interface{}] struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: ctx, tokenExpiration, claims
func (_m *JWTHelper[Claims]) GenerateToken(ctx context.Context, tokenExpiration time.Duration, claims Claims) (string, int64, error) {
	ret := _m.Called(ctx, tokenExpiration, claims)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, Claims) (string, int64, error)); ok {
		return rf(ctx, tokenExpiration, claims)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration, Claims) string); ok {
		r0 = rf(ctx, tokenExpiration, claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration, Claims) int64); ok {
		r1 = rf(ctx, tokenExpiration, claims)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, time.Duration, Claims) error); ok {
		r2 = rf(ctx, tokenExpiration, claims)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ValidateToken provides a mock function with given fields: encodedToken
func (_m *JWTHelper[Claims]) ValidateToken(encodedToken string) (*Claims, error) {
	ret := _m.Called(encodedToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*Claims, error)); ok {
		return rf(encodedToken)
	}
	if rf, ok := ret.Get(0).(func(string) *Claims); ok {
		r0 = rf(encodedToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(encodedToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewJWTHelper creates a new instance of JWTHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTHelper[Claims interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTHelper[Claims] {
	mock := &JWTHelper[Claims]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
