// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Span is an autogenerated mock type for the Span type
type Span struct {
	mock.Mock
}

// End provides a mock function with no fields
func (_m *Span) End() {
	_m.Called()
}

// RecordError provides a mock function with given fields: err
func (_m *Span) RecordError(err error) {
	_m.Called(err)
}

// SetAttributes provides a mock function with given fields: attrs
func (_m *Span) SetAttributes(attrs map[string]interface{}) {
	_m.Called(attrs)
}

// NewSpan creates a new instance of Span. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpan(t interface {
	mock.TestingT
	Cleanup(func())
}) *Span {
	mock := &Span{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
