// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	telemetry "github.com/Luis-Miguel-BL/go-lm-template/internal/application/telemetry"
)

// Telemetry is an autogenerated mock type for the Telemetry type
type Telemetry struct {
	mock.Mock
}

// AddAttributes provides a mock function with given fields: ctx, attrs
func (_m *Telemetry) AddAttributes(ctx context.Context, attrs map[string]interface{}) context.Context {
	ret := _m.Called(ctx, attrs)

	if len(ret) == 0 {
		panic("no return value specified for AddAttributes")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) context.Context); ok {
		r0 = rf(ctx, attrs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// AddEvent provides a mock function with given fields: ctx, event
func (_m *Telemetry) AddEvent(ctx context.Context, event telemetry.Event) {
	_m.Called(ctx, event)
}

// GetServerMiddlewares provides a mock function with no fields
func (_m *Telemetry) GetServerMiddlewares() []interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServerMiddlewares")
	}

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func() []interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

// NewHttpTransport provides a mock function with no fields
func (_m *Telemetry) NewHttpTransport() http.RoundTripper {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewHttpTransport")
	}

	var r0 http.RoundTripper
	if rf, ok := ret.Get(0).(func() http.RoundTripper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.RoundTripper)
		}
	}

	return r0
}

// RecordError provides a mock function with given fields: ctx, err
func (_m *Telemetry) RecordError(ctx context.Context, err error) {
	_m.Called(ctx, err)
}

// RecordMetric provides a mock function with given fields: ctx, metric
func (_m *Telemetry) RecordMetric(ctx context.Context, metric telemetry.Metric) {
	_m.Called(ctx, metric)
}

// Shutdown provides a mock function with given fields: ctx
func (_m *Telemetry) Shutdown(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartSpan provides a mock function with given fields: ctx, name
func (_m *Telemetry) StartSpan(ctx context.Context, name string) (context.Context, telemetry.Span) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for StartSpan")
	}

	var r0 context.Context
	var r1 telemetry.Span
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, telemetry.Span)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) telemetry.Span); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(telemetry.Span)
		}
	}

	return r0, r1
}

// TraceIDFromContext provides a mock function with given fields: ctx
func (_m *Telemetry) TraceIDFromContext(ctx context.Context) string {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TraceIDFromContext")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewTelemetry creates a new instance of Telemetry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelemetry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Telemetry {
	mock := &Telemetry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
